---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: 'Shoreline Provider'
subcategory: ''
description: |-
---

# Shoreline Provider

[Shoreline.io](https://shoreline.io/) provides real-time, automatic remediation for cloud operations.

_Automatic remediation_ centralizes auto-healing processes by preventing or fixing repetitive incidents without human intervention.

The Shoreline Provider and associated [Op Packs](https://docs.shoreline.io/op/packs) are remediation as code tools. You can easily integrate Shoreline's automated monitoring, debugging, and repairing capabilities within your Terraform configuration.

-> _Remediation as code_ adds auto-remediation tool creation and management to the same high-level, codified pipeline as the rest of your operations configuration.

Check out [Getting Started with Shoreline](https://docs.shoreline.io/getting-started) for more details!

## Example Usage

The following configuration creates a basic auto-remediation loop within Shoreline via Terraform:

- The [Alarm](https://docs.shoreline.io/alarms) defines when there is an issue.
- The [Action](https://docs.shoreline.io/actions) defines what to do about the issue.
- The [Bot](https://docs.shoreline.io/bots) connects the two by triggering the [Action](https://docs.shoreline.io/actions) when the [Alarm](https://docs.shoreline.io/alarms) fires.

{{tffile "examples/aaa/basic.tf"}}

{{ .SchemaMarkdown | trimspace }}
